### ISSUE TITLE
Using this in a ASP.NET Core 2.0 project results in this

### ISSUE THREAD

**Issue by SuperJMN** [IdentityServer/IdentityServer4.AccessTokenValidation#75]
![image](https://user-images.githubusercontent.com/3109851/30057346-aaa3eac4-9236-11e7-98bc-8fe0ed6148c5.png)

**error CS7069: Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found**

Is it caused because this library is incompatible with ASP.NET Core 2.0?

Please, tell us if it's going to be fixed soon. 
Thanks!

**Comment by leastprivilege** [comment]
We are working on it.

**Comment by SuperJMN** [comment]
Do you have an estimated release plan? We need to connect to our corporate Active Directory Federation Services from ASP.NET and we don't know any alternative to your library :( 

Please, share as much information as you can.

Thank you!

**Comment by leastprivilege** [comment]
I just pushed 2.0.0-rc1 to nuget. Give it a try.

**Comment by leastprivilege** [comment]
Tracking this in #72.

**Comment by yaronzo** [comment]
I am a bit confused. Why is the issue closed?

I tried 2.0.0-rc1 and I am still facing the same problem (“Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found”).

Any solutions?

I am just using the following code in the client side
app.UseIdentityServerAuthentication(
                new IdentityServerAuthenticationOptions
                {
                    Authority = "http://localhost:5000",
                    RequireHttpsMetadata = false,
                    ValidateScope = true,
                    ApiName = apiName,
                    //AutomaticAuthenticate = true,
                    //AutomaticChallenge = true,
                    AllowedScopes = { apiName },
                    EnableCaching=false // TODO: =true
                    , ApiSecret= "blabla"//.Sha256()
                });

**Comment by yaronzo** [comment]
Does it means that we have to use other libraries for the client (API) which do not support introspection till the issue get solved?

**Comment by leastprivilege** [comment]
We pushed a rc1 to nuget.

**Comment by TheFrogPrince** [comment]
With 2.0.0-rc1, I get 
`
'IApplicationBuilder' does not contain a definition for 'UseIdentityServerAuthentication' and no extension method 'UseIdentityServerAuthentication' accepting a first argument of type 'IApplicationBuilder' could be found
`

a bit maddening.  Can't see the extension method anywhere in the Object Browser either.  If I roll back to 1.2.1, then I can see the method in the Object Browser, but then I get the 
`Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found
`

Having flashbacks to the 90s.  :)  Not trying to rush anyone, just curious, is the only way forward right now with ID4.Validation to drop my project back to Core 1?

**Comment by cbioley** [comment]
@TheFrogPrince `UseIdentityServerAuthentication` is gone:

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/commit/5ba378c09a8073d339c19ce40152a8fee7091a8f#diff-c1ce3f801529aee1d2de28674043763dL13

**Comment by TheFrogPrince** [comment]
Ah...  thank you.

https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Clients/src/SampleApi/Startup.cs#L23-L31

It hurts less when I quit banging my head against the wall.  :)

**Comment by cbioley** [comment]
@TheFrogPrince It's also refreshing to realize you're not the only one to bang it against your lowly wall ^^
